import { OnInit, OnChanges } from '@angular/core';
import { AbstractControl } from '@angular/forms';
import { JsonSchemaFormService } from '../json-schema-form.service';
import { DatePickerComponent } from 'ng2-date-picker';
export declare class DatetimepickerComponent implements OnInit, OnChanges {
    private jsf;
    formControl: AbstractControl;
    controlName: string;
    controlValue: any;
    dateValue: any;
    controlDisabled: boolean;
    boundControl: boolean;
    options: any;
    autoCompleteList: string[];
    mode: string;
    layoutNode: any;
    layoutIndex: number[];
    dataIndex: number[];
    datePicker: DatePickerComponent;
    theme: string;
    datePickerConfig: {
        firstDayOfWeek: string;
        format: string;
        monthFormat: string;
        disableKeypress: boolean;
        allowMultiSelect: boolean;
        closeOnSelect: boolean;
        closeOnSelectDelay: number;
        openOnFocus: boolean;
        openOnClick: boolean;
        onOpenDelay: number;
        weekDayFormat: string;
        appendTo: HTMLElement;
        showNearMonthDays: boolean;
        showWeekNumbers: boolean;
        enableMonthSelector: boolean;
        yearFormat: string;
        showGoToCurrent: boolean;
        dayBtnFormat: string;
        monthBtnFormat: string;
        hours12Format: string;
        hours24Format: string;
        meridiemFormat: string;
        minutesFormat: string;
        minutesInterval: number;
        secondsFormat: string;
        secondsInterval: number;
        showSeconds: boolean;
        showTwentyFourHours: boolean;
        timeSeparator: string;
        multipleYearsNavigateBy: number;
        showMultipleYearsNavigation: boolean;
        locale: string;
        hideInputContainer: boolean;
        returnedValueType: StringConstructor;
        unSelectOnClick: boolean;
        hideOnOutsideClick: boolean;
    };
    constructor(jsf: JsonSchemaFormService);
    ngOnInit(): void;
    ngOnChanges(): void;
    setControlDate(dateString: string): void;
    updateValue(event: any): void;
}
